apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "reops-ping"
  namespace: "team-researchops"
  labels:
    "team": "team-researchops"
spec:
  image: "{{image}}"
  port: 8080
  liveness:
    path: "internal/isalive"
  readiness:
    path: "internal/isready"
  replicas:
    min: 2
    max: 2
  prometheus:
    enabled: false
    path: "/internal/metrics"
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 256Mi
  ingresses:
    - https://ping.intern.nav.no/
    - https://ping.nav.no/event
  env:
    - name: GCS_BATCH_SIZE
      value: "3000"
    - name: GCS_MAX_INTERVAL_SECONDS
      value: "30"
    - name: GCS_BUCKET_PREFIX_EVENT
      value: "gs://{{ bucket.name }}/events"
    - name: GCS_BUCKET_PREFIX_ATTRIBUTE
      value: "gs://{{ bucket.name }}/events-attributes"
  gcp:
    buckets:
      - name: "{{ bucket.name }}"
        publicAccessPrevention: true
        lifecycleCondition:
          age: 3 # days
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic